apiVersion: apps/v1
kind: Deployment
metadata:
  name: nirmata-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nirmata-nginx
        image: nginx
