apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: limit-containers-per-pod
spec:
  validationFailureAction: audit
  background: false
  rules:
  - name: limit-containers-per-pod-controllers
    match:
      resources:
        kinds:
        - Deployment
        - DaemonSet
        - Job
        - StatefulSet
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: Equal
        value: CREATE
    validate:
      message: "Pods can only have a maximum of 4 containers."
      deny:
        conditions:
          any:
          - key: "{{request.object.spec.template.spec.containers[] | length(@)}}"
            operator: GreaterThan
            value: "4"
  - name: limit-containers-per-pod-bare
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: Equal
        value: CREATE
    validate:
      message: "Pods can only have a maximum of 4 containers."
      deny:
        conditions:
          any:
          - key: "{{request.object.spec.containers[] | length(@)}}"
            operator: GreaterThan
            value: "4"
  - name: limit-containers-per-pod-cronjob
    match:
      resources:
        kinds:
        - CronJob
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: Equal
        value: CREATE
    validate:
      message: "Pods can only have a maximum of 4 containers."
      deny:
        conditions:
          any:
          - key: "{{request.object.spec.jobTemplate.spec.template.spec.containers[] | length(@)}}"
            operator: GreaterThan
            value: "4"
